### ISSUE TITLE
No Gradle compatible dependency notation

### ISSUE THREAD

**Issue by st0nx** [echocat/gradle-golang-plugin#2]
```
dependencies {
    build 'github.com/urfave/cli'
    test 'github.com/stretchr/testify'
}
```

> Supplied String module notation 'github.com/urfave/cli' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

**Comment by blaubaer** [comment]
You are right @st0nx, but I thing normally every (current) go developer uses definitions of dependencies (right now) in notation like `github.com/urfave/cli` etc. 

I already played around with things like:
- `github.com:urfave:cli`
- `github.com:urfave.cli`
  ...

But in all this cases I have potential clashes with other kinds of notations.

Do you have an idea for this?

**Comment by st0nx** [comment]
Maybe, use this way https://github.com/bat-cha/gradle-plugin-git-dependencies ?

**Comment by blaubaer** [comment]
This is a technical possibility. But the question is what are the advantages?

| Facts | `github.com/urfave/cli` | `com.github.urfave:cli:1.2` |
| --- | --- | --- |
| Like other Gradle project dependency definitions |  | :heavy_check_mark: |
| Like golang developers known dependency definitions | :heavy_check_mark: |  |
| Short dependency description | :heavy_check_mark: |  |

Or did I missed a technical fact or something else?

**Comment by blaubaer** [comment]
I got no response within the last 14 days. Close the issue now.
