### ISSUE TITLE
What is importExtractor (this plugin wants to run this program)

### ISSUE THREAD

**Issue by ghost** [echocat/gradle-golang-plugin#5]
``` sh
$ gradle build
:validate
:prepare-toolchain
:get-tools UP-TO-DATE
:prepare-sources
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> java.io.IOException: Cannot run program "~/.go/sdk/go1.6.2/bin/importsExtractor": error=2, No such file or directory
```

What is this program and why do you think I should have it? (This is the directory where this plugin downloads its stuff).

**Comment by blaubaer** [comment]
[`importExtractor`](../tree/master/src/main/resources/org/echocat/gradle/plugins/golang/utils/importsExtractor.go) is genereted while [`prepareToolchain` task](../tree/master/src/main/java/org/echocat/gradle/plugins/golang/tasks/PrepareToolchain.java). It is used to resolve the dependency tree.  If you exclude the `prepareToolchain` task this failure will occur in the build steps. 

Could you verify this?

**Comment by blaubaer** [comment]
I was able to reproduce the bug also with working prepareToolchain task. I will fix this.
